### ISSUE TITLE
Make changes according to wikitolearn new API

### ISSUE THREAD

**Issue by hackertron** [hackertron/WikiDesktopClient#9]
Recently the API was changed . Now the page retrieval is not working properly because pages have shifted to new location/url . 

Construct the URL's accordingly to get the pages .

**Comment by Nitish18** [comment]
@hackertron  Hi, can I work on this issue ??
Can you tell me some more detail about the Issue ?? 
Thanks a lot.

**Comment by hackertron** [comment]
Hey you are free to work but before that tell me are you familiar with QML and Qt ? 
below are some resources for you to look around 
1. this will show you what's basic idea of application : https://www.youtube.com/watch?v=8ChDasnf9SM
2. this is a working demo : https://www.youtube.com/watch?v=MGyl-M-Q8ZY
3. Docs :  http://wtld.readthedocs.io/en/latest/?badge=latest

lastly the WikiTolearn API : http://en.wikitolearn.org/api.php

P.S. if you  are not familiar with Qt (C++) and QML don't worry . i will post more tasks soon  :)

**Comment by Nitish18** [comment]
Hi @hackertron ,
I am familiar with QML & Qt. I frequently contribute to GCompris project which is based on Qml & QtQuick.

**Comment by hackertron** [comment]
you can work on it (y)  . You are free to ask anything .

**Comment by Nitish18** [comment]
Hi @hackertron ,
I tried to build the project on my Ubuntu. But, when I ran it on QtCreator 5.4.0 it gave me an error :-
**Project ERROR: Unknown module(s) in QT: webview quickcontrols2
updatePchInfo: switching to none**

I searched & found out it's a QtWebengine problem. So,could you tell me what dependencies I am missing in this case.

Thanks.

**Comment by hackertron** [comment]
First of all update your qt version to Qt5.7 . There are many new features in 5.7 that i am  using . 

docs on how to setup : http://wtld.readthedocs.io/en/latest/docs/code-docs/how-to-setup/

**Comment by hackertron** [comment]
Hello ,  i am sorry but this issue can't be fixed right now . WikiTolearn 1.0 new version is going to release soon and there will more changes again . 

read here : https://blogs.wikitolearn.org/2016/10/wiki-whats-going-part-15-its-been-while/

So i think it would be better till we wait for 1.0 else we have to redo the same work !! :( 

Thank you for showing interest in the topic . 

P.S. i will create some documentation related issues , if you like you can work on it !!

**Comment by Nitish18** [comment]
That's Ok . Nice interacting with you :)
